version: '3.8'

services:
  app:
    build: .
    container_name: stream-vault-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=${DB_USER:-video_user}
      - DB_PASSWORD=${DB_PASSWORD:-db_password}
      - DB_NAME=${DB_NAME:-video_db}
      - DB_PORT=${DB_PORT:-5432}
      - SESSION_SECRET=${SESSION_SECRET:-stream-vault-secret}
      - SESSION_MAX_AGE=${SESSION_MAX_AGE:-86400000}
      - DEFAULT_QUALITY=${DEFAULT_QUALITY:-all}
      - USE_GPU=${USE_GPU:-false}
      - AUTO_TRANSCODE=${AUTO_TRANSCODE:-true}
    volumes:
      - ./media:/app/media
      - ./upload:/app/upload
    networks:
      - stream-vault-network

  db:
    image: postgres:14-alpine
    container_name: stream-vault-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER:-video_user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-db_password}
      - POSTGRES_DB=${DB_NAME:-video_db}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c 'max_connections=100'
    networks:
      - stream-vault-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-video_user} -d ${DB_NAME:-video_db}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:

networks:
  stream-vault-network:
    driver: bridge
