version: '3.8'

services:
  app:
    build: .
    container_name: stream-vault-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=video_user
      - DB_PASSWORD=db_password
      - DB_NAME=video_db
      - DB_PORT=5432
    volumes:
      - ./media:/app/media
      - ./upload:/app/upload

  db:
    image: postgres:14-alpine
    container_name: stream-vault-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=video_user
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=video_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c 'max_connections=100'

volumes:
  postgres_data:
